WriteAll: use delegate instead of Expression
adamhathcock/sharpcompress pull request #683
Opened 2022-07-18 01:36 UTC by OwnageIsMagic

2022-07-18 09:50 UTC, adamhathcock approved these changes

2022-07-19 01:02 UTC, OwnageIsMagic commented on src/SharpCompress/Writers/IWriterExtensions.cs
> +                                    Func<string, bool>? fileSearchFunc = null,
```suggestion
                                    Predicate<string>? fileSearchFunc = null,
```

2022-07-26 15:22 UTC, adamhathcock requested changes
Looks like func is required unless you change the `Where`

2022-07-26 18:34 UTC, OwnageIsMagic reviewed
WriteAll: revert 109a7c12ead9893

2022-07-27 08:49 UTC, adamhathcock approved these changes

2022-07-27 09:13 UTC, merged