LHA archive decompression support added
adamhathcock/sharpcompress pull request #731
Opened 2023-03-08 19:17 UTC by TwanVanDongen

LHA Archive support added for decompression of methods lh0, lh5, lh6 and lh7. Others will be added when test-archives are created. Implementation taken from [LHA Decompressor for .NET](https://github.com/benbaker76/LHADecompressor), which is a port of [LHA Decompressor for Java](https://sourceforge.net/projects/lhadecompressor/).

2023-03-09 09:34 UTC, adamhathcock requested changes
Never heard of LHA!

Some minor things but the major is the LICENSE which is LGPL and we're MIT

Unless you got permission, I can't accept code from https://github.com/benbaker76/LHADecompressor/tree/master unfortunately

2023-03-09 09:34 UTC, adamhathcock commented on .gitignore
> +/src/SharpCompress/Readers/ReaderFactory.cs
This doesn't seem right

2023-03-09 09:34 UTC, adamhathcock commented on src/SharpCompress/Archives/Lha/LhaArchive.cs
> +#nullable disable
Not a fan but can overlook for this PR

2023-03-09 09:34 UTC, adamhathcock commented on tests/SharpCompress.Test/SharpCompress.Test.csproj
> +    <Compile Remove="Lha\LhaReaderTests.cs" />
Seems wrong

2023-03-09 17:57 UTC, TwanVanDongen commented on .gitignore
> +/src/SharpCompress/Readers/ReaderFactory.cs
yep, accidentally removed it, but it's back now!

2023-03-09 17:58 UTC, TwanVanDongen commented on src/SharpCompress/Archives/Lha/LhaArchive.cs
> +#nullable disable
also not too happy about it, but saw that it was accepted elsewhere; certainly want to fix it where code is accepted

2023-03-09 17:59 UTC, TwanVanDongen commented on tests/SharpCompress.Test/SharpCompress.Test.csproj
> +    <Compile Remove="Lha\LhaReaderTests.cs" />
Started implementing also the reader function, but removed it in order to get the 'Archive' support in first.

2023-03-24 18:15 UTC, TwanVanDongen commented
> Never heard of LHA!
> 
> Some minor things but the major is the LICENSE which is LGPL and we're MIT
> 
> Unless you got permission, I can't accept code from https://github.com/benbaker76/LHADecompressor/tree/master unfortunately

Received confirmation from Headkaze's to use his C# port of LHADecompressor (" I have no problem with you using my port. I believe it's the same license as the original source. If it complies then it shouldn't be a problem."). This however only resolved the porting, now trying to connect the original Java developer (Nobuyasu SUEHIRO)  with the same question.

2023-07-04 11:07 UTC, vpenades commented
Suggestion:  If the problem is only the license, an alternative approach would be this:

Create a separate project library called **SharpCompress.ArchiveFormat.LHA** (or something like that) which would use the LGPL license, so it would be license compatible.

Users willing to use LHA would require:

- To be also license compatible with LGPL
- Reference SharpCompress
- Reference SharpCompress.ArchiveFormat.LHA
- register the LHA factory at application startup

2023-07-04 14:16 UTC, adamhathcock commented
that's a good call, to do that.  Can register factories at start up now with little code

2024-01-27 17:16 UTC, closed without merging